# Dataset root directory relative to the yolov5 directory
path: szh_dataset_512

# Train/val/test sets: specify directories, *.txt files, or lists
train: images/trn
val: images/val
test: images/tst

names:
  0: manhole