services:
  streetview:
    build: .
    volumes:
      - ./data:/app/data
      - ./config:/app/config
      - ./outputs:/app/outputs
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    command: /bin/bash
    shm_size: 4g