get_stat_images.py:
  working_directory: .
  input_folder: /mnt/s3/proj-streetview/02_data/01_initial/01_images/Innovitas_2024/

prepare_coco_data.py:
  working_directory: .
  original_COCO_files:
    RCNE: data/RCNE/Object_Detect_GT/ne_COCO.json
    SZH: data/SZH/zh_COCO_13033.json
  validated_COCO_files:
    RCNE: data/RCNE/Object_Detect_GT/valid_ne_250725.json
    SZH: data/SZH/valid_zh_250825.json
  clipping_params:
    RCNE:
      width: 8000
      height: 4000
      overlap_x: 44
      overlap_y: 8
      padding_y: 736
    SZH:
      lb4:
        width: 2048
        height: 2048
        overlap_x: 0
        overlap_y: 0
        padding_y: 0
      else:
        width: 4016
        height: 4016
        overlap_x: 74
        overlap_y: 74
        padding_y: 0
  ratio_wo_annotations: 0.33
  seed: 42
  overwrite_images: False
  tasks:
    test_only: False
    make_other_dataset: True
    coco:
      prepare_data: True
      subfolder: outputs/<DETECTRON2_FOLDER>
    yolo:
      prepare_data: False
      subfolder: outputs/<COCO_FOR_YOLO_FOLDER>

train_detectron2.py:
  debug_mode: False
  working_directory: outputs/<DETECTRON2_FOLDER>
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_training_images
  resume_training: False
  COCO_files:
    trn: COCO_trn.json
    val: COCO_val.json
    tst: COCO_tst.json
  detectron2_config_file: ../../../config/detectron2/detectron2_config.yaml
  model_weights:
    # pth_file: logs/model_0054999.pth
    model_zoo_checkpoint_url: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml


infer_with_detectron2.py:
  working_directory: outputs/<DETECTRON2_FOLDER>
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files:           # relative paths, w/ respect to the working_folder
    trn: COCO_trn.json
    val: COCO_val.json
    tst: COCO_tst.json
    oth: COCO_oth.json
  detectron2_config_file: ../../../config/detectron2/detectron2_config.yaml # path relative to the working_folder
  model_weights:
    pth_file: logs/model_0092499.pth # trained model minimizing the validation loss, monitor via tensorboard (tensorboard --logdir </logs>)
  score_lower_threshold: 0.05


assess_detections.py:
  working_directory: outputs/<DETECTRON2_FOLDER>
  output_folder: eval
  datasets:
    path_ground_truth: .
    ground_truth_files:
      trn: COCO_trn.json
      val: COCO_val.json
      tst: COCO_tst.json
    path_detections: .
    detections_files:
      trn: trn_detections_at_0dot05_threshold.json
      val: val_detections_at_0dot05_threshold.json
      tst: tst_detections_at_0dot05_threshold.json
  # limit_aoi: SZH
  # confidence_threshold: 0.4