transform_detections.py:
  working_directory: .
  output_folder: outputs/OD
  image_dir: data/RCNE/panoramic_images
  detections_files:
    trn: outputs/OD/trn_detections_at_0dot05_threshold.json
    val: outputs/OD/val_detections_at_0dot05_threshold.json
    tst: outputs/OD/tst_detections_at_0dot05_threshold.json
  panoptic_coco_files:
    RCNE: data/RCNE/Object_Detect_GT/valid_ne_250626.json
  score_threshold: 0.2


clipped_labels_to_panoramic.py:
  working_directory: .
  output_folder: outputs/OD
  image_dir: data/RCNE/panoramic_images
  labels_files:
    trn: outputs/OD/COCO_trn.json
    val: outputs/OD/COCO_val.json
    tst: outputs/OD/COCO_tst.json
  panoptic_coco_files:
    RCNE: data/RCNE/Object_Detect_GT/valid_ne_250626.json


assess_detections.py:
  working_directory: outputs/OD
  output_folder: panoptic_eval
  metrics_method: micro-average
  datasets:
    ground_truth_files:
      trn: trn_COCO_panoptic_labels.json
      val: val_COCO_panoptic_labels.json
      tst: tst_COCO_panoptic_labels.json
    detections_files:
      trn: trn_COCO_panoptic_detections.json
      val: val_COCO_panoptic_detections.json
      tst: tst_COCO_panoptic_detections.json


visualize_results.py:
  working_directory: .
  output_folder: outputs/OD/panoptic_eval/images_for_visualization
  image_folder: data/RCNE/panoramic_images
  tagged_COCO_files:
    all:  outputs/OD/panoptic_eval/tagged_detections.json
    # trn: trn_COCO_panoptic_detections.json
    # val: val_COCO_panoptic_detections.json
    # tst: tst_COCO_panoptic_detections.json
  coco_file_for_images: data/RCNE/Object_Detect_GT/valid_ne_250626.json