transform_detections.py:
  working_directory: .
  output_folder: outputs/yolo/infer/run01
  image_dir: /mnt/s3/proj-streetview/02_data/01_initial/01_images/NE_2020_pano
  detections_files:
    trn: outputs/yolo/infer/run01/YOLO_trn_detections.json
    val: outputs/yolo/infer/run01/YOLO_val_detections.json
    tst: outputs/yolo/infer/run01/YOLO_tst_detections.json
  panoptic_coco_files:
    RCNE: data/RCNE/Object_Detect_GT/valid_ne_250626.json
    SZH: data/SZH/valid_zh_250731.json
  id_correspondence: outputs/detectron2_both/original_ids.csv
  score_threshold: 0.20


clipped_labels_to_panoramic.py:
  working_directory: .
  output_folder: outputs/yolo/infer
  image_dir: /mnt/s3/proj-streetview/02_data/01_initial/01_images/NE_2020_pano
  labels_files:
    trn: outputs/coco_for_yolo_conversion/trn.json
    val: outputs/coco_for_yolo_conversion/val.json
    tst: outputs/coco_for_yolo_conversion/tst.json
  panoptic_coco_files:
    RCNE: data/RCNE/Object_Detect_GT/valid_ne_250626.json
    SZH: data/SZH/valid_zh_250731.json
  id_correspondence: outputs/detectron2_both/original_ids.csv


assess_detections.py:
  working_directory: outputs/yolo
  output_folder: panoptic_eval
  metrics_method: micro-average
  datasets:
    path_ground_truth: infer
    ground_truth_files:
      trn: trn_COCO_panoptic_labels.json
      val: val_COCO_panoptic_labels.json
      tst: tst_COCO_panoptic_labels.json
    path_detections: infer/run01
    detections_files:
      trn: trn_COCO_panoptic_detections.json
      val: val_COCO_panoptic_detections.json
      tst: tst_COCO_panoptic_detections.json


visualize_results.py:
  working_directory: .
  output_folder: outputs/yolo/panoptic_eval/images_for_visualization
  tagged_COCO_files:
    tagged:  outputs/yolo/panoptic_eval/tagged_detections.json
    # trn: trn_COCO_panoptic_detections.json
    # val: val_COCO_panoptic_detections.json
    # tst: tst_COCO_panoptic_detections.json
  coco_file_for_images:
      trn: trn_COCO_panoptic_detections.json
      val: val_COCO_panoptic_detections.json
      tst: tst_COCO_panoptic_detections.json
  # image_ids: [
  #   4120,
  #   4121,
  #   4122,
  #   4123,
  #   4214,
  #   4125,
  #   4126,
  #   4127,
  #   4128,
  #   4129
  # ]