prepare_coco_data.py:
  working_directory: outputs
  image_dir: /mnt/s3/proj-streetview/02_data/01_initial/01_images/NE_2020_pano
  COCO_files:
    RCNE: data/RCNE/Object_Detect_GT/coco_ne.json
  cached_validation:
    RCNE: data/RCNE/Object_Detect_GT/valid_ne_250625.json
  ratio_wo_annotations: 0
  seed: 42
  overwrite_images: False
  tasks:
    make_other_dataset: True
    yolo:
      prepare_data: True
      subfolder: coco_for_yolo_conversion

coco_to_yolo.py:
  working_directory: outputs
  input_folder: coco_for_yolo_conversion
  output_folder: datasets/RCNE_datasets_512

redistribute_images.py:
  working_directory: outputs/coco_for_yolo_conversion
  image_folder: .
  output_folder: ../datasets/RCNE_datasets_512/images
  COCO_files:
    trn: trn.json
    val: val.json
    tst: tst.json
  overwrite: False

tune_yolo_model.py:
  working_directory: outputs
  project: yolo/tune
  model: yolo11m-seg.pt
  params:
    # https://docs.ultralytics.com/usage/cfg/#train-settings
    epochs: 100
    patience: 50    # Number of epochs to wait without improvement in validation metrics before early stopping (default 100)
  
tune_yolo_w_ray.py:
  output_folder: /home/gsalamin/Documents/GitHub/proj-streetview/outputs/ray_tune # relative path not supported

plot_best.py:
  working_directory: outputs
  ray_results_dir: ray_tune

train_yolo.py:
  working_directory: outputs
  project: yolo/train
  name: run
  model: yolo11s-seg.pt
  best_parameters_path: /home/gsalamin/ray_results/train_yolo_2025-07-15_14-14-00/train_yolo_f3a76_00007_7_batch=20,lr0=0.0050,model=yolo11s-seg,optimizer=SGD,patience=25_2025-07-15_14-14-01/params.json
  resume_training: False

validate_yolo.py:
  working_directory: outputs
  project: yolo/train
  model: yolo/train/run00/weights/best.pt
  best_parameters_path: /home/gsalamin/ray_results/train_yolo_2025-07-15_14-14-00/train_yolo_f3a76_00007_7_batch=20,lr0=0.0050,model=yolo11s-seg,optimizer=SGD,patience=25_2025-07-15_14-14-01/params.json

infer_with_yolo.py:
  working_directory: outputs
  project: yolo/infer
  model: yolo/train/run00/weights/best.pt
  dataset_images_folder:
    trn: datasets/RCNE_datasets_512/images/trn
    val: datasets/RCNE_datasets_512/images/val
    tst: datasets/RCNE_datasets_512/images/tst
  coco_info_folder: coco_for_yolo_conversion

assess_detections.py:
  working_directory: outputs/yolo
  output_folder: eval
  metrics_method: micro-average
  datasets:
    path_ground_truth: ../coco_for_yolo_conversion
    ground_truth_files:
      trn: trn.json
      val: val.json
      tst: tst.json
    path_detections: infer/run00
    detections_files:
      trn: YOLO_trn_detections.json
      val: YOLO_val_detections.json
      tst: YOLO_tst_detections.json