transform_detections.py:
  working_directory: .
  output_folder: outputs/detectron2_both
  detections_files:
    trn: outputs/detectron2_both/trn_detections_at_0dot05_threshold.json
    val: outputs/detectron2_both/val_detections_at_0dot05_threshold.json
    tst: outputs/detectron2_both/tst_detections_at_0dot05_threshold.json
    oth: outputs/detectron2_both/oth_detections_at_0dot05_threshold.json
  panoptic_coco_files:
    RCNE: data/RCNE/Object_Detect_GT/valid_ne_250626.json
    SZH: data/SZH/valid_zh_250731.json
  id_correspondence: outputs/detectron2_both/original_ids.csv
  score_threshold: 0.20


clipped_labels_to_panoramic.py:
  working_directory: .
  output_folder: outputs/detectron2_both
  labels_files:
    trn: outputs/detectron2_both/COCO_trn.json
    val: outputs/detectron2_both/COCO_val.json
    tst: outputs/detectron2_both/COCO_tst.json
  panoptic_coco_files:
    RCNE: data/RCNE/Object_Detect_GT/valid_ne_250626.json
    SZH: data/SZH/valid_zh_250731.json
  id_correspondence: outputs/detectron2_both/original_ids.csv


assess_detections.py:
  working_directory: outputs/detectron2_both
  output_folder: panoptic_eval
  metrics_method: micro-average
  datasets:
    ground_truth_files:
      trn: trn_COCO_panoptic_labels.json
      val: val_COCO_panoptic_labels.json
      tst: tst_COCO_panoptic_labels.json
    detections_files:
      trn: trn_COCO_panoptic_detections.json
      val: val_COCO_panoptic_detections.json
      tst: tst_COCO_panoptic_detections.json


visualize_results.py:
  working_directory: outputs/detectron2_both
  output_folder: panoptic_eval/images_for_visualization
  tagged_COCO_files:
    all:  panoptic_eval/tagged_detections.json
    oth: oth_COCO_panoptic_detections.json
    # trn: trn_COCO_panoptic_detections.json
    # val: val_COCO_panoptic_detections.json
    # tst: tst_COCO_panoptic_detections.json
  coco_file_for_images:
      trn: trn_COCO_panoptic_detections.json
      val: val_COCO_panoptic_detections.json
      tst: tst_COCO_panoptic_detections.json
  # image_ids: [
  #   4120,
  #   4121,
  #   4122,
  #   4123,
  #   4214,
  #   4125,
  #   4126,
  #   4127,
  #   4128,
  #   4129
  # ]