prepare_coco_data.py:
  working_directory: .
  original_COCO_files:
    # RCNE: data/RCNE/Object_Detect_GT/ne_COCO.json
    SZH: data/SZH/zh_COCO_13033.json
  validated_COCO_files:
    # RCNE: data/RCNE/Object_Detect_GT/valid_ne_250725.json
    SZH: data/SZH/valid_zh_250731.json
  clipping_params:
    RCNE:
      width: 8000
      height: 4000
      overlap_x: 44
      overlap_y: 8
      padding_y: 736
    SZH:
      width: 2048
      height: 2048
      overlap_x: 0
      overlap_y: 0
      padding_y: 0
  ratio_wo_annotations: 0.33
  seed: 42
  overwrite_images: False
  tasks:
    make_other_dataset: True
    yolo:
      prepare_data: True
      subfolder: outputs/coco_for_yolo_conversion_szh

coco_to_yolo.py:
  working_directory: outputs
  input_folder: coco_for_yolo_conversion_szh
  output_folder: datasets/szh_dataset_512

redistribute_images.py:
  working_directory: outputs/coco_for_yolo_conversion_szh
  image_folder: .
  output_folder: ../datasets/szh_dataset_512/images
  COCO_files:
    trn: trn.json
    val: val.json
    tst: tst.json
    oth: oth.json
  overwrite: False

tune_yolo_model.py:
  working_directory: outputs
  project: yolo/tune
  model: yolo11m-seg.pt
  params:
    # https://docs.ultralytics.com/usage/cfg/#train-settings
    epochs: 100
    patience: 50    # Number of epochs to wait without improvement in validation metrics before early stopping (default 100)
  
tune_yolo_w_ray.py:
  output_folder: /mnt/data-volume-02/gsalamin/GitHub/proj-streetview/outputs/ray_tune # relative path not supported

plot_best.py:
  working_directory: outputs
  ray_results_dir: ray_tune

train_yolo.py:
  working_directory: outputs
  project: yolo/train
  name: run
  best_parameters_path: ray_tune/train_yolo_2025-08-07_09-54-30/train_yolo_833b5_00037_37_epochs=75,freeze=0,lr0=0.0030,lrf=0.0100,model=yolo11m-seg,optimizer=SGD_2025-08-07_09-54-30/params.json
  resume_training: False

validate_yolo.py:
  working_directory: outputs
  project: yolo/train
  model: yolo/train/run03/weights/best.pt

infer_with_yolo.py:
  working_directory: outputs
  project: yolo/infer
  model: yolo/train/run03/weights/best.pt
  dataset_images_folder:
    trn: datasets/szh_dataset_512/images/trn
    val: datasets/szh_dataset_512/images/val
    tst: datasets/szh_dataset_512/images/tst
    oth: datasets/szh_dataset_512/images/oth
  coco_info_folder: coco_for_yolo_conversion_szh

assess_detections.py:
  working_directory: outputs/yolo
  output_folder: eval
  metrics_method: micro-average
  datasets:
    path_ground_truth: ../coco_for_yolo_conversion_szh
    ground_truth_files:
      trn: trn.json
      val: val.json
      tst: tst.json
    path_detections: infer/run03
    detections_files:
      trn: YOLO_trn_detections.json
      val: YOLO_val_detections.json
      tst: YOLO_tst_detections.json