transform_detections.py:
  working_directory: .
  output_folder: outputs/yolo/infer/<MODEL_FOLDER>
  detections_files:
    trn: outputs/yolo/infer/<MODEL_FOLDER>/YOLO_trn_detections.json
    val: outputs/yolo/infer/<MODEL_FOLDER>/YOLO_val_detections.json
    tst: outputs/yolo/infer/<MODEL_FOLDER>/YOLO_tst_detections.json
    oth: outputs/yolo/infer/<MODEL_FOLDER>/YOLO_oth_detections.json
  panoptic_coco_files:
    RCNE: data/RCNE/Object_Detect_GT/valid_ne_250725.json
    SZH: data/SZH/valid_zh_250825.json
  id_correspondence: outputs/original_ids.csv
  score_threshold: 0.35


clipped_labels_to_panoramic.py:
  working_directory: .
  output_folder: outputs/yolo/infer/<MODEL_FOLDER>
  labels_files:
    trn: outputs/<COCO_FOR_YOLO_FOLDER>/trn.json
    val: outputs/<COCO_FOR_YOLO_FOLDER>/val.json
    tst: outputs/<COCO_FOR_YOLO_FOLDER>/tst.json
  panoptic_coco_files:
    RCNE: data/RCNE/Object_Detect_GT/valid_ne_250725.json
    SZH: data/SZH/valid_zh_250825.json
  id_correspondence: outputs/original_ids.csv


assess_detections.py:
  working_directory: outputs/<DETECTRON2_FOLDER>
  output_folder: panoptic_eval
  datasets:
    path_ground_truth: .
    ground_truth_files:
      trn: trn_COCO_panoptic_labels.json
      val: val_COCO_panoptic_labels.json
      tst: tst_COCO_panoptic_labels.json
    path_detections: .
    detections_files:
      trn: trn_COCO_panoptic_detections.json
      val: val_COCO_panoptic_detections.json
      tst: tst_COCO_panoptic_detections.json
  confidence_threshold: 0.45
  # limit_aoi: SZH


visualize_results.py:
  working_directory: outputs/yolo
  output_folder: panoptic_eval/images_for_visualization
  tagged_COCO_files:
    tagged:  panoptic_eval/tagged_detections.json
    oth: infer/run03/oth_COCO_panoptic_detections.json
  coco_file_for_images:
      trn: infer/run03/trn_COCO_panoptic_detections.json
      val: infer/run03/val_COCO_panoptic_detections.json
      tst: infer/run03/tst_COCO_panoptic_detections.json
      oth: infer/run03/oth_COCO_panoptic_detections.json