coco_to_yolo.py:
  working_directory: outputs
  input_folder: COCO_datasets
  output_folder: YOLO_datasets

redistribute_images.py:
  working_directory: outputs
  image_folder: COCO_datasets
  output_folder: YOLO_datasets
  COCO_files:
    trn: COCO_datasets/trn.json
    val: COCO_datasets/val.json
    tst: COCO_datasets/tst.json
  overwrite: False

tune_yolo_model.py:
  working_directory: outputs
  # output_folder: yolov11
  # sample_tagged_img_subfolder: sample_training_images
  yolo_file: ../config/yolo/yolo_dataset.yaml
  model: yolo11n-seg.pt
  resume_training: False
  params:
    # https://medium.com/internet-of-technology/yolov8-best-practices-for-training-cdb6eacf7e4f
    batch: 1
    epochs: 100
    # lr0: 0.01
    # lrf: 0.01
    patience: 50    # Number of epochs to wait without improvement in validation metrics before early stopping (default 100)
  