transform_detections.py:
  working_directory: .
  output_folder: outputs/detectron2
  image_dir: data/RCNE/panoramic_images
  detections_files:
    # trn: outputs/detectron2/trn_detections_at_0dot05_threshold.json
    # val: outputs/detectron2/val_detections_at_0dot05_threshold.json
    # tst: outputs/detectron2/tst_detections_at_0dot05_threshold.json
    oth: outputs/detectron2/oth_detections_at_0dot05_threshold.json
  panoptic_coco_files:
    RCNE: data/RCNE/Object_Detect_GT/valid_ne_250626.json
  score_threshold: 0.05


clipped_labels_to_panoramic.py:
  working_directory: .
  output_folder: outputs/detectron2
  image_dir: data/RCNE/panoramic_images
  labels_files:
    trn: outputs/detectron2/COCO_trn.json
    val: outputs/detectron2/COCO_val.json
    tst: outputs/detectron2/COCO_tst.json
  panoptic_coco_files:
    RCNE: data/RCNE/Object_Detect_GT/valid_ne_250626.json


assess_detections.py:
  working_directory: outputs/detectron2
  output_folder: panoptic_eval
  metrics_method: micro-average
  datasets:
    ground_truth_files:
      trn: trn_COCO_panoptic_labels.json
      val: val_COCO_panoptic_labels.json
      tst: tst_COCO_panoptic_labels.json
    detections_files:
      trn: trn_COCO_panoptic_detections.json
      val: val_COCO_panoptic_detections.json
      tst: tst_COCO_panoptic_detections.json


visualize_results.py:
  working_directory: .
  output_folder: outputs/detectron2/panoptic_eval/images_for_visualization
  image_folder: data/RCNE/panoramic_images
  tagged_COCO_files:
    all:  outputs/detectron2/panoptic_eval/tagged_detections.json
    # trn: trn_COCO_panoptic_detections.json
    # val: val_COCO_panoptic_detections.json
    # tst: tst_COCO_panoptic_detections.json
  coco_file_for_images: data/RCNE/Object_Detect_GT/valid_ne_250626.json
  # image_ids: [
  #   4120,
  #   4121,
  #   4122,
  #   4123,
  #   4214,
  #   4125,
  #   4126,
  #   4127,
  #   4128,
  #   4129
  # ]