prepare_coco_data.py:
  working_directory: .
  original_COCO_files:
    RCNE: data/RCNE/Object_Detect_GT/ne_COCO.json
    SZH: data/SZH/zh_COCO_13033.json
  validated_COCO_files:
    RCNE: data/RCNE/Object_Detect_GT/valid_ne_250725.json
    SZH: data/SZH/valid_zh_250731.json
  clipping_params:
    RCNE:
      width: 8000
      height: 4000
      overlap_x: 44
      overlap_y: 8
      padding_y: 736
    SZH:
      lb4:
        width: 2048
        height: 2048
        overlap_x: 0
        overlap_y: 0
        padding_y: 0
      else:
        width: 4016
        height: 4016
        overlap_x: 74
        overlap_y: 74
        padding_y: 0
  ratio_wo_annotations: 0
  seed: 42
  overwrite_images: False
  tasks:
    make_other_dataset: True
    yolo:
      prepare_data: True
      subfolder: outputs/<COCO_FOR_YOLO_FOLDER>

coco_to_yolo.py:
  working_directory: outputs
  input_folder: <COCO_FOR_YOLO_FOLDER>
  output_folder: datasets/<YOLO_DATASET>

redistribute_images.py:
  working_directory: outputs/<COCO_FOR_YOLO_FOLDER>
  image_folder: .
  output_folder: ../datasets/<YOLO_DATASET>/images
  COCO_files:
    trn: trn.json
    val: val.json
    tst: tst.json
    oth: oth.json
  overwrite: False

tune_yolo_model.py:
  working_directory: outputs
  project: yolo/tune
  model: yolo11m-seg.pt
  params:
    # https://docs.ultralytics.com/usage/cfg/#train-settings
    epochs: 100
    patience: 50    # Number of epochs to wait without improvement in validation metrics before early stopping (default 100)
  
tune_yolo_w_ray.py:
  output_folder: /mnt/data-volume-02/gsalamin/GitHub/proj-streetview/outputs/ray_tune # relative path not supported

plot_best.py:
  working_directory: outputs
  ray_results_dir: ray_tune

train_yolo.py:
  working_directory: outputs
  project: yolo/train
  name: run
  best_parameters_path: ray_tune/train_yolo_2025-08-07_09-54-30/train_yolo_833b5_00037_37_epochs=75,freeze=0,lr0=0.0030,lrf=0.0100,model=yolo11m-seg,optimizer=SGD_2025-08-07_09-54-30/params.json
  resume_training: False

validate_yolo.py:
  working_directory: outputs
  project: yolo/train
  model: yolo/train/<MODEL_FOLDER>/weights/best.pt

infer_with_yolo.py:
  working_directory: outputs
  project: yolo/infer
  model: yolo/train/<MODEL_FOLDER>/weights/best.pt
  dataset_images_folder:
    trn: datasets/<YOLO_DATASET>/images/trn
    val: datasets/<YOLO_DATASET>/images/val
    tst: datasets/<YOLO_DATASET>/images/tst
    oth: datasets/<YOLO_DATASET>/images/oth
  coco_info_folder: <COCO_FOR_YOLO_FOLDER>

assess_detections.py:
  working_directory: outputs/yolo
  output_folder: eval
  metrics_method: micro-average
  datasets:
    path_ground_truth: ../<COCO_FOR_YOLO_FOLDER>
    ground_truth_files:
      trn: trn.json
      val: val.json
      tst: tst.json
    path_detections: infer/<MODEL_FOLDER>
    detections_files:
      trn: YOLO_trn_detections.json
      val: YOLO_val_detections.json
      tst: YOLO_tst_detections.json