transform_detections.py:
  working_directory: .
  output_folder: outputs/<DETECTRON2_FOLDER>/
  detections_files:
    trn: outputs/<DETECTRON2_FOLDER>/trn_detections_at_0dot05_threshold.json
    val: outputs/<DETECTRON2_FOLDER>/val_detections_at_0dot05_threshold.json
    tst: outputs/<DETECTRON2_FOLDER>/tst_detections_at_0dot05_threshold.json
    oth: outputs/<DETECTRON2_FOLDER>/oth_detections_at_0dot05_threshold.json
  panoptic_coco_files:
    RCNE: data/RCNE/Object_Detect_GT/ne_COCO.json
    SZH: data/SZH/zh_COCO_13033.json
  id_correspondence: outputs/<DETECTRON2_FOLDER>/original_ids.csv
  score_threshold: 0.2


clipped_labels_to_panoramic.py:
  working_directory: .
  output_folder: outputs/<DETECTRON2_FOLDER>
  labels_files:
    trn: outputs/<DETECTRON2_FOLDER>/COCO_trn.json
    val: outputs/<DETECTRON2_FOLDER>/COCO_val.json
    tst: outputs/<DETECTRON2_FOLDER>/COCO_tst.json
  panoptic_coco_files:
    RCNE: data/RCNE/Object_Detect_GT/ne_COCO.json
    SZH: data/SZH/zh_COCO_13033.json
  id_correspondence: outputs/<DETECTRON2_FOLDER>/original_ids.csv


assess_detections.py:
  working_directory: outputs/<DETECTRON2_FOLDER>
  output_folder: SZH/panoptic_eval
  datasets:
    path_ground_truth: .
    ground_truth_files:
      trn: trn_COCO_panoptic_labels.json
      val: val_COCO_panoptic_labels.json
      tst: tst_COCO_panoptic_labels.json
    path_detections: .
    detections_files:
      trn: trn_COCO_panoptic_detections.json
      val: val_COCO_panoptic_detections.json
      tst: tst_COCO_panoptic_detections.json
  confidence_threshold: 0.45
  limit_aoi: SZH


visualize_results.py:
  working_directory: outputs/yolo
  output_folder: panoptic_eval/images_for_visualization
  tagged_COCO_files:
    tagged:  panoptic_eval/tagged_detections.json
    oth: infer/run03/oth_COCO_panoptic_detections.json
  coco_file_for_images:
      trn: infer/run03/trn_COCO_panoptic_detections.json
      val: infer/run03/val_COCO_panoptic_detections.json
      tst: infer/run03/tst_COCO_panoptic_detections.json
      oth: infer/run03/oth_COCO_panoptic_detections.json