get_stat_images.py:
  working_directory: .
  input_folder: /mnt/s3/proj-streetview/02_data/01_initial/01_images/Innovitas_2024/

prepare_coco_data.py:
  working_directory: .
  output_dir: outputs/detectron2_test
  image_dir: 
    RCNE: data/RCNE/panoramic_images/
    SZH: /mnt/s3/proj-streetview/02_data/01_initial/01_images/Innovitas_2024/
  original_COCO_files:
    RCNE: data/RCNE/Object_Detect_GT/ne_COCO.json
    SZH: data/SZH/zh_COCO_13033.json
  validated_COCO_files:
    RCNE: data/RCNE/Object_Detect_GT/valid_ne_250725.json
    SZH: data/SZH/valid_zh_250731.json
  clipping_params:
    RCNE:
      width: 8000
      height: 4000
      overlap_x: 44
      overlap_y: 8
      padding_y: 736
    SZH:
      width: 2048
      height: 1024
      overlap_x: 0
      overlap_y: 0
      padding_y: 0
  ratio_wo_annotations: 0.5
  seed: 42
  make_other_dataset: True
  overwrite_images: False

train_model.py:
  debug_mode: False
  working_directory: outputs/detectron2
  log_subfolder: logs
  sample_tagged_img_subfolder: sample_training_images
  resume_training: False
  COCO_files:
    trn: COCO_trn.json
    val: COCO_val.json
    tst: COCO_tst.json
  detectron2_config_file: ../../config/detectron2_config.yaml
  model_weights:
    model_zoo_checkpoint_url: COCO-InstanceSegmentation/mask_rcnn_R_50_FPN_1x.yaml
  
make_inference.py:
  working_directory: outputs/detectron2
  sample_tagged_img_subfolder: sample_tagged_images
  COCO_files:           # relative paths, w/ respect to the working_folder
    trn: COCO_trn.json
    val: COCO_val.json
    tst: COCO_tst.json
    oth: COCO_oth.json
  detectron2_config_file: ../../config/detectron2_config.yaml # path relative to the working_folder
  model_weights:
    pth_file: logs/model_0011999.pth # trained model minimizing the validation loss, monitor via tensorboard (tensorboard --logdir </logs>)
  image_metadata_json: img_metadata.json
  score_lower_threshold: 0.05


assess_detections.py:
  working_directory: outputs/detectron2
  output_folder: eval
  metrics_method: micro-average
  datasets:
    ground_truth_files:
      trn: COCO_trn.json
      val: COCO_val.json
      tst: COCO_tst.json
    detections_files:
      trn: trn_detections_at_0dot05_threshold.json
      val: val_detections_at_0dot05_threshold.json
      tst: tst_detections_at_0dot05_threshold.json